# Generated by Django 6.0.6 on 2026-07-07 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_medicalrecord_date_time_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name', 'Doctor')), on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'Patient')), on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name', 'Doctor')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_medical_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
