# Generated by Django 6.0.6 on 2026-07-19 19:53

import office.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_alter_appointment_date_time_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attachment',
            field=models.FileField(blank=True, help_text='Allowed file types: PDF, JPG, PNG, WebP, GIF, BMP, TIFF (Max 10MB)', null=True, upload_to='appointments/', validators=[office.models.validate_appointment_attachment]),
        ),
    ]
