# Generated by Django 6.0.6 on 2026-07-25 23:33

import office.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_appointment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='attachment',
            field=models.FileField(blank=True, help_text='Allowed file types: PDF, JPG, PNG, WebP, GIF, BMP, TIFF (Max 10MB)', null=True, upload_to=office.models.appointment_attachment_upload_to, validators=[office.models.validate_appointment_attachment]),
        ),
    ]
