# Generated by Django 6.0.7 on 2026-08-05 02:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_appointment_last_reminder_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'date_time', 'last_reminder_sent_at'], name='office_appo_status_05ee76_idx'),
        ),
    ]
